// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
  namespace App {
    interface Platform {
      env: Env;
      ctx: ExecutionContext;
      caches: CacheStorage;
      cf?: IncomingRequestCfProperties;
    }

    // interface Error {}
    interface Locals {
      staff: import('@regional-quiz/shared').StaffClaims | null;
      participant: import('@regional-quiz/shared').ParticipantClaims | null;
    }
    // interface PageData {}
    // interface PageState {}
  }
}

// Merged into the ambient `Env` interface declared by the generated
// `worker-configuration.d.ts` (regenerated by `wrangler types`, not
// hand-edited). `SESSION_SECRET` is a secret provisioned out-of-band via
// `wrangler secret put` / the Cloudflare Pages dashboard, so it never
// appears in `wrangler.jsonc`.
interface Env {
  SESSION_SECRET: string;
}

export {};
