// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
  namespace App {
    interface Platform {
      env: Env;
      ctx: ExecutionContext;
      caches: CacheStorage;
      cf?: IncomingRequestCfProperties;
    }

    // interface Error {}
    interface Locals {
      staff: import('@regional-quiz/shared').StaffClaims | null;
      participant: import('@regional-quiz/shared').ParticipantClaims | null;
    }
    // interface PageData {}
    // interface PageState {}
  }

  // Cloudflare's Turnstile API, published by the script
  // `$lib/components/Turnstile.svelte` adds to the head. Only the calls that
  // component makes are declared; `window.turnstile` is absent until that
  // script has loaded, which is why it is optional.
  interface Window {
    turnstile?: {
      render(
        container: HTMLElement,
        options: {sitekey: string},
      ): string | undefined;
      // `widget` is the id `render` returned, or the container element --
      // which is the only handle there is on a widget the script rendered
      // by itself.
      reset(widget: string | HTMLElement): void;
    };
  }
}

// Merged into the ambient `Env` interface declared by the generated
// `worker-configuration.d.ts` (regenerated by `wrangler types`, not
// hand-edited). `SESSION_SECRET` is a secret provisioned out-of-band via
// `wrangler secret put` / the Cloudflare Pages dashboard, so it never
// appears in `wrangler.jsonc`.
interface Env {
  SESSION_SECRET: string;
  // The origin of the backend Worker that `hooks.server.ts` forwards
  // `/api/*` to. Not a secret, but it differs per environment (preview vs.
  // production), so it is set as a Pages environment variable rather than
  // hard-coded in `wrangler.jsonc`. Locally it comes from `.env`.
  BACKEND_URL: string;
}

export {};
